apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1 # Número de pods a serem criados
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: etdacorp/helloworld:1.0 # Imagem do Docker da sua aplicação
        ports:
        - containerPort: 8080 # Porta que a aplicação escuta dentro do container